### PR TITLE
Use bitflags 0.5 in the breaks branch

### PR DESCRIPTION
**Pull request by saurvs**
Part of https://github.com/servo/servo/issues/10077.

### CODE REVIEW

**Comment by sfackler** [comment]
Doesn't appear to compile: https://travis-ci.org/sfackler/rust-openssl/builds/118684997

**Comment by gkoz** [comment]
Bitflags 0.5 makes everything private by default. you can't just bump the version, you need to change `flags Foo: ...` to `pub flags Foo: ...`.

**Comment by saurvs** [comment]
I added `pub` but it doesn't fix it because it the `ffi_extras` and `ffi` namespaces aren't being resolved for some reason. It works fine if the constants from those modules are replaced with literals. Any idea why this is happening?

**Comment by sfackler** [comment]
Covered by #385

**Pull request closed without merging**
