### PR TITLE
Also link to libatomic for android static 32 bit 3.0.0 builds

### PR DESCRIPTION
**Pull request by ValHeimer**
I only added the android target beside linux

Resolves https://github.com/sfackler/rust-openssl/issues/1555

### CODE REVIEW

**Comment by sfackler** [comment]
Just to confirm, what's the compilation error you run into without this change?

**Comment by ValHeimer** [comment]
> Just to confirm, what's the compilation error you run into without this change?

You can find the compilation error described in the following pull request: https://github.com/rusqlite/rusqlite/pull/1037

Initially I thought it was about rusqlite but actually the problem seems to come from this crate since it is where the linking process takes place.

**Comment by sfackler** [comment]
Cool, thanks! I will cut a new release tonight.

**Comment by sfackler** [comment]
Done!

**Pull request merged**
