### PR TITLE
Make X509_PURPOSE opaque for LibreSSL >= 3.9.0

### PR DESCRIPTION
**Pull request by botovq**
As discussed in https://github.com/sfackler/rust-openssl/pull/2115

### CODE REVIEW

**Review by alex — APPROVED** [review]

**Comment by alex** [comment]
As an aside, do you have any sense of when 3.9.0 will be out?

**Comment by botovq** [comment]
There are no concrete plans. I do not expect it to happen earlier second half of February. But it might be quite a later. Is there anything you're blocking on?

**Comment by alex** [comment]
Not particularly, so no rush.

**Comment by Sp1l** [comment]
FWIW... LibreSSL 3.9.1 is now release, together with OpenBSD 7.5

**Pull request merged**
