### PR TITLE
Add get_security_bits for PKey

### PR DESCRIPTION
**Pull request by steffen-eiden**
Signed-off-by: Steffen Eiden <seiden@linux.ibm.com>

### CODE REVIEW

**Comment by sfackler** [comment]
Looks like there are some clippy errors on the test but looks good to me otherwise.

**Comment by steffen-eiden** [comment]
> Looks like there are some clippy errors on the test but looks good to me otherwise.
> 
> It also seems like the function was renamed at some point in OpenSSL.
yeah, I thought I got all positions where I had to add the old name function. But didn't

**Comment by steffen-eiden** [comment]
Got all the nitty details correct now.

Please squash when merging.

Thanks.

**Comment by sfackler** [comment]
Thanks!

**Comment by steffen-eiden** [comment]
You are welcome

**Pull request merged**
