### PR TITLE
don't emit rerun-if-changed when vendoring

### PR DESCRIPTION
**Pull request by reaperhulk**

### CODE REVIEW

**Review by alex — APPROVED** [review]

**Comment by jonhoo** [comment]
@alex Any chance of getting a release with the fix — makes my editor sad now 😅

**Comment by alex** [comment]
I can do one tonight.

**Comment by ryzhyk** [comment]
Thanks for the fix @reaperhulk ! Also looking forward to the crates release to unbreak our software :)

**Comment by alex** [comment]
Ok, release is out.

**Comment by alekspickle** [comment]
thx for fixing this quickly, I was trying to figure out why my laptop is learning how to fly away

**Pull request merged**
