### PR TITLE
openssl-sys: support libressl 2.6.1

### PR DESCRIPTION
**Pull request by Keruspe**
systest currently fails as cms.h doesn't exist anymore, not sure how to make it conditional

### CODE REVIEW

**Comment by sfackler** [comment]
The systest crate should be able to get access to the `libressl261` in its build script.

Is there any semantic meaning at all to major, minor, and patch version bumps to the libressl folks? It's not clear to me why removing a public API header would happen in a patch release.

**Comment by Keruspe** [comment]
If you're speaking of doing what my second commit does, I already tried and it doesn't seem to work either. Am I missing something there?

**Comment by sfackler** [comment]
They aren't passed as cfgs, but rather as environment variables: https://github.com/sfackler/rust-openssl/blob/master/openssl/build.rs

**Comment by sfackler** [comment]
Can you bump this build to use 2.6.1 rather than 2.6.0? https://github.com/sfackler/rust-openssl/blob/master/.circleci/config.yml#L81

**Comment by Keruspe** [comment]
@sfackler I can't seem to find where the env variables are set. Currently I see that DEP_OPENSSL_LIBRESSL is true, and DEP_OPENSSL_VERSION is 101 which doesn't help me special-casing libressl 2.6.1

**Comment by Keruspe** [comment]
I got it to build, now looking in a few tests failures:

```
bad SSL_OP_ALL value at byte 0: rust: 20 (0x14) != c 4 (0x4)                                              
bad SSL_OP_ALL value at byte 3: rust: 128 (0x80) != c 0 (0x0)                                             
bad SSL_OP_SINGLE_ECDH_USE value at byte 2: rust: 8 (0x8) != c 0 (0x0)                                    
bad SSL_OP_TLSEXT_PADDING value at byte 0: rust: 16 (0x10) != c 0 (0x0)                                   
bad SSL_OP_CRYPTOPRO_TLSEXT_BUG value at byte 3: rust: 128 (0x80) != c 0 (0x0)      
```

**Comment by sfackler** [comment]
Cool - you'll have to conditionally adjust those constants in openssl-sys sounds like.

**Comment by Keruspe** [comment]
This last commit might need some further digging? I don't see it specifically mentioned in the release notes

**Comment by sfackler** [comment]
Yeah, that seems a bit suspicious.

**Comment by sfackler** [comment]
Seems like it could be this line in the changelog?

> * Cleaned up the EC key/curve configuration handling.

**Comment by Keruspe** [comment]
The man page for set_tmp_ecdh now states that the this function is now a noop, so I guess that last change is right after all

**Comment by sfackler** [comment]
Ok - thanks!

**Pull request merged**
