### PR TITLE
add support for SSL_CTX_set_options and SSL_CTX_get_options

### LINKED ISSUE #168: SslContext should expose some way to set options on the underlying SSL_CTX
This is done via OpenSSL's `SSL_CTX_set_options` function, this is necessary to pass `SSL_OP_NO_SSLv2` and `SSL_OP_NO_SSLv3` (to say nothing of the variety of other options there, but these are the ones I care about at this moment)

### PR DESCRIPTION
**Pull request by reaperhulk**
This is the first rust I've ever written so I'd appreciate any pointers if there are ways to write it better (especially the tests).

fixes #168

### CODE REVIEW

**Comment by sfackler** [comment]
Thanks! Could you add bindings for `SSL_CTX_clear_options` too?

I'm not a huge fan of passing a raw `c_long` around - the `bitflags` crate should be able to give us a slightly nicer API. Could you add `const`s for all of the options to `openssl-sys` and make an `SslCtxOptions` wrapper type with `bitflags!` in `openssl::ssl`? http://doc.rust-lang.org/bitflags/bitflags/macro.bitflags!.html#example

Looks good other than those two things.

**Comment by reaperhulk** [comment]
@sfackler thanks, I'll take a look at revise this PR.

**Comment by reaperhulk** [comment]
(PR has been revised with bitflags and clear_options)

**Comment by sfackler** [comment]
Thanks!

**Pull request merged**
