### PR TITLE
Fix build on *BSD

### PR DESCRIPTION
**Pull request by wg**
FreeBSD includes OpenSSL in the base system, and I believe OpenBSD includes their fork known as LibreSSL.

### CODE REVIEW

**Comment by sfackler** [comment]
Is pkg-config unable to find the copy of OpenSSL?

**Comment by wg** [comment]
@sfackler yup, I assume because pkg-config itself is a package whereas OpenSSL is part of the base system.

**Comment by sfackler** [comment]
Ok, it looks like this is an issue in general with BSDs: https://bugs.freedesktop.org/show_bug.cgi?id=14247. Can you add a comment on the block briefly explaining why BSD is special cased? Looks good other than that, thanks!

**Comment by wg** [comment]
Great, thanks! Cargo build is currently broken on FreeBSD due to this issue, could you push another revision that includes it?

**Comment by sfackler** [comment]
Published v0.3.5

**Comment by gkoz** [comment]
Note that FreeBSD also has OpenSSL available from ports so unconditionally linking to the base system one might not be the best idea.

**Comment by sfackler** [comment]
@gkoz good point. I moved the BSD special case to after the pkg-config checks which should make it do the right thing more often.

**Pull request merged**
