### PR TITLE
fix cross compile with target i686-linux-android

### PR DESCRIPTION
**Pull request by chshawkn**
fix https://github.com/sfackler/rust-openssl/issues/625

### CODE REVIEW

**Comment by sfackler** [comment]
I believe this is due to a fix in libc's definition of c_char on Android. Does the build work on using nightly Rust?

**Comment by chshawkn** [comment]
I didn't try nightly Rust.

**Comment by sfackler** [comment]
Everything should work fine as is if you use a rustc that includes https://github.com/rust-lang/rust/pull/40317.

**Comment by chshawkn** [comment]
@sfackler Thanks. You are right, it works!

**Pull request closed without merging**
