### PR TITLE
Add Blowfish support

### PR DESCRIPTION
**Pull request by 0xa**

### CODE REVIEW

**Comment by sfackler** [comment]
Thanks!

Looks like one of these is a macro which the tests are not happy with: https://github.com/openssl/openssl/blob/6f0ac0e2f27d9240516edb9a23b7863e7ad02898/include/openssl/evp.h#L732

**Comment by sfackler** [comment]
Cool, looks like tests are happy. Could you add some tests to make sure these behave as expected? Looks like there are some test vectors you can use here: https://www.schneier.com/code/vectors.txt

**Comment by 0xa** [comment]
Those are without padding I think and would require calling .pad(false) somewhere, how would you prefer that done?

**Comment by sfackler** [comment]
That seems fine to disable padding if those test vectors require it.

**Comment by sfackler** [comment]
Thanks!

**Pull request merged**
