### PR TITLE
Add function to write RSA public key as PEM

### PR DESCRIPTION
**Pull request by andrew-d**

### CODE REVIEW

**Comment by andrew-d** [comment]
@sfackler Worth noting that the failed checks don't appear to be a problem with these changes.

**Comment by sfackler** [comment]
The travis error should be fixed if you rebase.

**Comment by andrew-d** [comment]
Okay, looks like the failures are either something strange about AppVeyor, or a failure to fetch packages from Cargo.

**Comment by sfackler** [comment]
Yep, appveyor's failing because I haven't gotten around to setting it up.

Looks good to me, thanks!

**Pull request merged**
