### PR TITLE
Fix static openssl-sys build on windows-gnu

### LINKED ISSUE #1014: Cross compiling openssl-sys to Windows with mingw fails if vendored
The build fails when trying to find the built static/dynamic libraries. The reason seems to be that with mingw (as opposed to msvc) .a files are created. Since both targets are treated equally here:
https://github.com/sfackler/rust-openssl/blob/b88778bc76b039e26aaa3d54f03716433986fae1/openssl-sys/build/main.rs#L85

...the build ends up looking for liblibssl.a and fails.

### PR DESCRIPTION
**Pull request by pyfqm**
Fixes #1014.

### CODE REVIEW

**Comment by pyfqm** [comment]
@sfackler any progress?

**Comment by fleimgruber** [comment]
@pyfqm ping for rebase as I would test this if I could patch cleanly.

**Comment by abcfy2** [comment]
Same issue here. Please merge this pull request.

**Comment by laumann** [comment]
Just chiming in to say that I'd also be interested in seeing this merged :smile: Thanks for a great library @sfackler

**Comment by laumann** [comment]
@pyfqm I think this one can be closed, as #1265 has been merged to fix the same issue.

**Pull request closed without merging**
