### PR TITLE
Sync with libressl 3.5.0

### PR DESCRIPTION
**Pull request by gonzalo-**
I hope I am not missing any file :)

https://marc.info/?l=libressl&m=164572407401570&w=2

### CODE REVIEW

**Comment by vishwin** [comment]
Some of this looks wrong, especially with supporting older versions. Compare with #1528

**Comment by oherrala** [comment]
LibreSSL 3.5.2 was released few days ago (2022-04-23):

> We have released LibreSSL 3.5.2, which will be arriving in the LibreSSL directory of your local OpenBSD mirror soon. This is the first stable release for the 3.5.x branch, also available with OpenBSD 7.1

Release notes: https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-3.5.2-relnotes.txt

**Comment by vishwin** [comment]
Been aware.

**Comment by sfackler** [comment]
#1628

**Pull request closed without merging**
