### PR TITLE
Set SSL_MODE_RELEASE_BUFFERS by default

### LINKED ISSUE #696: SSL_MODE_RELEASE_BUFFERS on by default?
I've been informed that it's quite common in almost all production codebases to turn this option on by default and apparently [Python also switch to do this](https://bugs.python.org/issue25672) awhile ago!

Although maybe this is explicitly left out?

### PR DESCRIPTION
**Pull request by alexcrichton**
Closes #696

### CODE REVIEW

**Comment by sfackler** [comment]
My only worry here is around people running super old versions of OpenSSL becoming vulnerable to CVE 2014-0198. They've had 3 years to upgrade, though, so maybe that's not a huge concern at this point?

**Comment by alexcrichton** [comment]
It actually may be easy enough to fix that, according to the Python thread it was fixed in 1.0.1h. Do you know what hex number that corresponds to to use `::version::number()`?

**Comment by sfackler** [comment]
It'd be `0x1000108f` I think?

**Comment by alexcrichton** [comment]
Updated!

**Pull request merged**
