### PR TITLE
Try harder to find OpenSSL when cross-compiling for a different Linux arch

### PR DESCRIPTION
**Pull request by mbr**
Debian (and probably many derivatives) package foreign architecture versions of libraries and allow parallel installation, this makes for very convenient cross-compilation. This usually works with other crates, but I haven't investigated whether this is due to no dynamic linking or if rust-openssl somehow breaks a working build process.

The PR does at least add the often correct path for the libs and assumes that the "regular" include directory is the one to use, which allows me to cross compile to `arm-unknown-linux-gnueabihf` from my `amd64` at least.

### CODE REVIEW

**Comment by sfackler** [comment]
Looks like this broke some of the builds.

How do C-based build systems find openssl/headers for cross builds?

**Comment by sfackler** [comment]
Ping

**Comment by mbr** [comment]
> How do C-based build systems find openssl/headers for cross builds?

I am not 100% sure, my understanding is that the default `-L` directories are either hardcoded or configured may vary from distro to distro. My debian system has a subfolder in `/usr/lib` and `/lib` for each arch:

```
$ find /usr/lib/ | grep libssl
/usr/lib/firefox-esr/libssl3.so
/usr/lib/i386-linux-gnu/i686/cmov/libssl.so.1.0.0
/usr/lib/i386-linux-gnu/i586/libssl.so.1.0.0
/usr/lib/i386-linux-gnu/libssl.so.1.0.0
/usr/lib/thunderbird/libssl3.so
/usr/lib/arm-linux-gnueabihf/libssl.a
/usr/lib/arm-linux-gnueabihf/pkgconfig/libssl.pc
/usr/lib/arm-linux-gnueabihf/libssl.so
/usr/lib/arm-linux-gnueabihf/libssl.so.1.0.0
/usr/lib/x86_64-linux-gnu/libssl.a
/usr/lib/x86_64-linux-gnu/pkgconfig/libssl.pc
/usr/lib/x86_64-linux-gnu/libssl.so
/usr/lib/x86_64-linux-gnu/libssl.so.1.0.0
/usr/lib/x86_64-linux-gnu/libssl3.so
```

I believe these are configured using `/etc/ld.so.conf`:

```
$ cat /etc/ld.so.conf
include /etc/ld.so.conf.d/*.conf
$ find /etc/ld.so.conf.d/
/etc/ld.so.conf.d/
/etc/ld.so.conf.d/i386-linux-gnu.conf
/etc/ld.so.conf.d/zz_i386-biarch-compat.conf
/etc/ld.so.conf.d/arm-linux-gnueabihf.conf
/etc/ld.so.conf.d/fakeroot-x86_64-linux-gnu.conf
/etc/ld.so.conf.d/libc.conf
/etc/ld.so.conf.d/x86_64-linux-gnu.conf
/etc/ld.so.conf.d/steam.conf
```

Looking into the config shows:

```
$ cat /etc/ld.so.conf.d/arm-linux-gnueabihf.conf
# Multiarch support
/lib/arm-linux-gnueabihf
/usr/lib/arm-linux-gnueabihf
$ cat /etc/ld.so.conf.d/x86_64-linux-gnu.conf
# Multiarch support
/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu
```

The details are probably somewhere in the `ldconfig` or `ld.so` manpages. =)

**Comment by sfackler** [comment]
Fundamentally, we need to be able to run the C preprocessor and have it find the openssl headers, and link to libcrypto and libssl. If they're in gcc's default search paths, then everything should work just fine, and if they're not we need to tell gcc where they live.

**Pull request closed without merging**
