### PR TITLE
Update README with OSX 10.11 instructions

### PR DESCRIPTION
**Pull request by winding-lines**
These instructions are from one of the open issues on the project. They are working for me, I am not sure if there are some possible side effects from the brew link --force.

### CODE REVIEW

**Comment by sfackler** [comment]
Force linking OpenSSL is a somewhat dangerous thing to do and I am pretty hesitant to recommend that course of action. It seems like a safer bet to use the environment variables already described to tell the build script specifically where to find the brew installed OpenSSL.

**Comment by winding-lines** [comment]
I've changed the README as per your feedback. 

One issue is that all the consumers of the openssl crate may have to setup the environment variables. Is this correct? If so could we integrate this in build.rs to reduce the development friction?

**Comment by sfackler** [comment]
Integrate it in what way? Adding `/usr/local/opt/openssl` to the search paths?

**Comment by winding-lines** [comment]
Yes, is that possible/desirable?

Marius
---

**Comment by sfackler** [comment]
Looks good to me with a rebase.

**Comment by erickt** [comment]
@winding-lines: got time to do this rebase?

**Comment by winding-lines** [comment]
I think I rebased :)

**Comment by gabeio** [comment]
:+1: just used that method to get this working thanks :smile:

**Comment by nox** [comment]
Couldn't build.rs set these environment variables itself?

**Comment by sfackler** [comment]
@nox the build.rs is what consumes them.

**Pull request merged**
