### PR TITLE
fix build err for taget `*-pc-windows-gnu`

### PR DESCRIPTION
**Pull request by nanpuyue**

### CODE REVIEW

**Comment by nanpuyue** [comment]
build err occur when `X86_64_PC_WINDOWS_GNU_OPENSSL_STATIC=1` was set:

深度截图_deepin-terminal_20190426162146

**Comment by sfackler** [comment]
Do you have a static copy of OpenSSL?

**Comment by nanpuyue** [comment]
of course:
深度截图_选择区域_20190426233630

**Comment by nanpuyue** [comment]
my commit fixed it.

**Comment by sfackler** [comment]
Oh right, the gnu toolchain isn't going to find normal Windows-style libraries anyway.

**Pull request merged**
