### PR TITLE
Initial support for OpenSSL 3.0.0-alpha17

### LINKED ISSUE #1263: Support OpenSSL 3.0.0
The first alpha has been released. I'm going to look into what support looks like. It claims to be broadly compatible with 1.1.1, but we'll see what happens.

### PR DESCRIPTION
**Pull request by sfackler**
Closes #1263

### CODE REVIEW

**Comment by sfackler** [comment]
Test failures are due to https://github.com/openssl/openssl/issues/12543.

**Comment by sahanaprasad07** [comment]
@sfackler Hello! OpenSSL 3.0 beta1 is expected to be released on June 30th [1]
Would this MR be merged after that?
Or is there any plan/possibility of it being merged earlier than the beta release?
Thank you!

[1] https://github.com/openssl/openssl/milestone/17

**Comment by sfackler** [comment]
I think I would probably wait for the stable release, but if the OpenSSL folks are planning on having a stable ABI starting with the beta releases we could land it earlier.

**Comment by sahanaprasad07** [comment]
With reference to the email [1], I think that would be the case.
It would be really nice to land this PR early.

[1] https://mta.openssl.org/pipermail/openssl-project/2021-April/002584.html

**Comment by cuviper** [comment]
Thanks @sfackler, much appreciated!

**Comment by sfackler** [comment]
https://github.com/openssl/openssl/issues/14863

**Comment by sfackler** [comment]
Ah great, we should be able to land this with the first beta then. There is still the risk of an ABI break, but it'll hopefully be low!

**Comment by wongsyrone** [comment]
Alpha 16 of OpenSSL 3.0 is now available

**Comment by wongsyrone** [comment]
I skimmed the upstream PR list. The changes in this PR are not sufficient to support OpenSSL 3.0. Many low-level APIs are deprecated and possibly removed starting 3.1.x.  It's a huge list, please check the links below to check the details.


ref:
The Draft PR:
https://github.com/openssl/openssl/pull/14710

https://github.com/openssl/openssl/blob/78537296ed95d35a31a0db868284854d2e7cbe5f/doc/man7/migration_guide.pod#deprecated-functions-in-openssl-3

**Comment by wongsyrone** [comment]
OpenSSL migration guide merged into the master branch: https://github.com/openssl/openssl/blob/master/doc/man7/migration_guide.pod

**Comment by satya-rajesh** [comment]
In which release will openssl 3.0.0 support added ?

**Comment by sfackler** [comment]
The release made yesterday.

**Pull request merged**
