### PR TITLE
Add LibreSSL support

### PR DESCRIPTION
**Pull request by semarie**
This PR adds LibreSSL support to rust-openssl.

It passed all tests with LibreSSL 2.5.1 (openssl, openssl-sys and systest).
Please note I had to disabling `dtlsv1` tests due to timeout issues.

Fixes: #521

### CODE REVIEW

**Comment by sfackler** [comment]
Awesome!

We'll want a Travis build against libressl - could you set that up?

**Comment by semarie** [comment]
I am unsure about to be able to setup Travis (I work on OpenBSD, not Linux). I could take a look, but there is no guarantee.

**Comment by semarie** [comment]
I will take a look tomorrow to see why my local build (under OpenBSD and with clang) doesn't have the errors present under Linux. I should have missed something.

**Comment by sfackler** [comment]
Sounds good, thanks!

Just to make sure, LibreSSL plans to continue being API compatible with some release of OpenSSL in the future, is that right?

**Comment by semarie** [comment]
For what I understood, LibreSSL should keep some API compatibility with OpenSSL. But some interfaces could be not implemented (if considered insane or unneed), or just enough for the API compatibility: as example, most of the flags values mismatch in Travis are commented as `Obsolete flags kept for compatibility. No sane code should use them.` in LibreSSL. I will ask for confirmation.

I wonder if the most straightforward approch shouldn't to start a `openssl-sys/src/libressl.rs` based on `ossl10x.rs`. It could take `ossl10x.rs` more readable, and will permit integrate LibreSSL changes independently from OpenSSL. But it also means duplicating code.

**Comment by sfackler** [comment]
Cool, that makes sense. Let's have a separate set of cfgs and feature flags for LibreSSL then.

**Comment by semarie** [comment]
@sfackler do you think this rewrite is good enough ?

**Comment by sfackler** [comment]
This seems good, thanks!

**Comment by Keruspe** [comment]
Could we get a release for this? :)

**Comment by sfackler** [comment]
Done!

**Pull request merged**
