### PR TITLE
Ssl session

### LINKED ISSUE #546: Can I access SSL_SESSION?
Is it possible to somehow access [SSL_SESSION](https://www.openssl.org/docs/man1.0.1/ssl/SSL.html) through this crate? 
I need to access the session key (at the server side) at some point. Is this currently possible?

### PR DESCRIPTION
**Pull request by sfackler**
@halmohri did you need any other functionality from SSL_SESSION?

Closes #546

### CODE REVIEW

**Comment by halmohri** [comment]
@sfackler Yes, I did want to have access to the shared secret key after handshake.

**Comment by sfackler** [comment]
Is that not the master key or the session ID?

**Comment by halmohri** [comment]
I don't think it's the session ID. I might be wrong but I think the agreed upon shared secret for a session is part of SSL_SESSION.

**Comment by sfackler** [comment]
Is it the `sid_ctx`? That's the only other thing that seems to fit.

**Comment by halmohri** [comment]
Isn't it the `master_key ` in `ssl_session_st`?

Openssl.org explains `SSL_SESSION`: 

> SSL_SESSION (SSL Session)
> This is a structure containing the current TLS/SSL session details for a connection: SSL_CIPHERs, client and server certificates, keys, etc.

**Comment by sfackler** [comment]
`SSL_SESSION` is a typedef of `struct ssl_session_st`.

**Comment by halmohri** [comment]
Yes. I know it's a typedef. I'm using `SSL_SESSION` and `ssl_session_st` interchangeably.

**Comment by sfackler** [comment]
Oh sorry, I was confused. Master key access is already there in the PR: https://github.com/sfackler/rust-openssl/pull/549/files#diff-e6acc97c6222cbc160517e2286040f19R1044

**Comment by halmohri** [comment]
I think if both master key and session ID are available, then life is good.

**Comment by sfackler** [comment]
Great!

**Pull request merged**
