### PR TITLE
Improved perfomance of vector allocation

### PR DESCRIPTION
**Pull request by iamnotacake**
Set length to capacity instead of filling vector with zeros

### CODE REVIEW

**Comment by sfackler** [comment]
Do you have any data comparing the performance before and after this change?

**Comment by sfackler** [comment]
Ping

**Comment by iamnotacake** [comment]
Pong. Sorry for so long silence. I performed _some_ tests and there was no difference. Maybe Rust optimizes the code. Or RAM I/O is very fast...

**Comment by sfackler** [comment]
Cool! I'd prefer to avoid messing around with uninitialized buffers unless there's a concrete performance need.

**Pull request closed without merging**
