### PR TITLE
Work In Progress; Wrap ECDSA functions

### PR DESCRIPTION
**Pull request by zsck**
This is not ready to be merged just yet.  I wanted to open a pull request as early as possible to start getting your feedback to ensure I am on the right track.  If you have some time, I'd love to know if this is looking good. I'll push new work into this branch as I have time.

### CODE REVIEW

**Comment by zsck** [comment]
@sfackler Do you know what the best thing to do about this is?
Apparently the use of EC_KEY here is problematic.  I've noticed that you've replaced some fields from the RSA struct with c_void pointers. Do you think I should do the same instead of wrapping EC_KEY, EC_GROUP etc?

```
src/lib.rs:787:37: 787:43 warning: found non-foreign-function-safe member in enum: found Rust slice type in foreign module, consider using a raw pointer instead, #[warn(improper_ctypes)] on by default
src/lib.rs:787     pub fn ECDSA_size(eckey: *const EC_KEY) -> c_int;
                                                   ^~~~~~
src/lib.rs:789:75: 789:81 warning: found non-foreign-function-safe member in enum: found Rust slice type in foreign module, consider using a raw pointer instead, #[warn(improper_ctypes)] on by default
src/lib.rs:789                       sig: *mut c_uchar, siglen: *mut c_uint, eckey: *mut EC_KEY) -> c_int;
                                                                                         ^~~~~~
src/lib.rs:790:77: 790:83 warning: found non-foreign-function-safe member in enum: found Rust slice type in foreign module, consider using a raw pointer instead, #[warn(improper_ctypes)] on by default
src/lib.rs:790     pub fn ECDSA_do_sign(dgst: *const c_uchar, dgst_len: c_int, eckey: *mut EC_KEY) -> *mut ECDSA_SIG;
                                                                                           ^~~~~~
src/lib.rs:792:73: 792:79 warning: found non-foreign-function-safe member in enum: found Rust slice type in foreign module, consider using a raw pointer instead, #[warn(improper_ctypes)] on by default
src/lib.rs:792                         sig: *const c_uchar, siglen: c_int, eckey: *mut EC_KEY) -> c_int;
                                                                                       ^~~~~~
src/lib.rs:794:63: 794:69 warning: found non-foreign-function-safe member in enum: found Rust slice type in foreign module, consider using a raw pointer instead, #[warn(improper_ctypes)] on by default
src/lib.rs:794                            sig: *const ECDSA_SIG, eckey: *mut EC_KEY) -> c_int;
                                                                             ^~~~~~
src/lib.rs:797:41: 797:47 warning: found non-foreign-function-safe member in enum: found Rust slice type in foreign module, consider using a raw pointer instead, #[warn(improper_ctypes)] on by default
src/lib.rs:797                             eckey: *mut EC_KEY) -> *mut ECDSA_SIG;
                                                       ^~~~~~
src/lib.rs:798:41: 798:47 warning: found non-foreign-function-safe member in enum: found Rust slice type in foreign module, consider using a raw pointer instead, #[warn(improper_ctypes)] on by default
src/lib.rs:798     pub fn ECDSA_sign_setup(eckey: *mut EC_KEY, ctx: *mut BN_CTX, kinv: *mut *mut BIGNUM, rp: *mut *mut BIGNUM) -> c_int;
                                                       ^~~~~~
src/lib.rs:801:78: 801:84 warning: found non-foreign-function-safe member in enum: found Rust slice type in foreign module, consider using a raw pointer instead, #[warn(improper_ctypes)] on by default
src/lib.rs:801                          kinv: *const BIGNUM, rp: *const BIGNUM, eckey: *mut EC_KEY) -> c_int;
                                                                                            ^~~~~~
```

**Comment by sfackler** [comment]
Looking good so far! These might need to be conditionally compiled if they only exist in newer versions of OpenSSL, but we'll figure that out when the code using these functions is added.

**Comment by andrewtj** [comment]
Are you still working on this @zsck?

**Comment by zsck** [comment]
@andrewtj I'm afraid not.

**Comment by sfackler** [comment]
Closing due to inactivity, but feel free to continue this in a new PR!

**Pull request closed without merging**
