### PR TITLE
Pass symmetric crypto initialization vector as a slice

### PR DESCRIPTION
**Pull request by jethrogb**
There is really no reason not to pass slices here.

Note: This change is backwards-incompatible. Users will need to turn their
parameters into references.

### CODE REVIEW

**Comment by gkoz** [comment]
Uh-oh, maybe I need to finish #173 at last. ;)

**Comment by sfackler** [comment]
If we change these signatures to e.g.

```rust
pub fn init<'a, T: As<&'a [u8]>(&self, mode: Mode, key: &[u8], iv: T) {
```

We can avoid breaking back-compat while allowing slices to be passed. It's a bit of a weird thing to use in the long term, so we'd probably switch back to a straight `&[u8]` at the next version bump.

**Comment by jethrogb** [comment]
Done. The syntax is `<T: AsRef<[u8]>>`.

**Comment by sfackler** [comment]
Thanks!

**Comment by sfackler** [comment]
Pushed the revert to the breaks branch: https://github.com/sfackler/rust-openssl/commit/db51bc43bdfd28d27c4826614fffb1576ef4b793

**Pull request merged**
