### PR TITLE
Update user32-sys and gdi32-sys to 0.2

### PR DESCRIPTION
**Pull request by nox**

### CODE REVIEW

**Comment by nox** [comment]
@sfackler We (Servo) will need a release again for this bump, hope that's not too much of a bother.

Cc @metajack.

**Comment by nox** [comment]
I've been informed by @retep998 that 0.1 shouldn't be depended upon anymore anyway (because they have "*" dependencies) and because it shouldn't cause any problem downstream. Feel free to do a minor or major bump, I don't care either way.

**Comment by sfackler** [comment]
Doesn't seem to build: https://ci.appveyor.com/project/sfackler/rust-openssl/build/1.0.595

**Comment by nox** [comment]
Sorry, brainfart. There wasn't any need to try to bump user32-sys since 0.1.2 at least already properly depend on winapi 0.2.

**Comment by nox** [comment]
I sound so confused it's not even funny. @retep998 just informed me that there should actually be a user32-sys 0.2. Stay tuned for the final modification when that is published.

**Comment by nox** [comment]
Done!

**Comment by retep998** [comment]
CI appear to have passed.

**Comment by sfackler** [comment]
I'll publish a new release when I get home tonight.

**Comment by nox** [comment]
Thanks!

**Comment by metajack** [comment]
Looks like you forgot. Reping @sfackler :)

**Comment by sfackler** [comment]
Done!

**Pull request merged**
