### PR TITLE
Attach cfg[allow_deprecated] to methods w/ uninitialized functionality

### PR DESCRIPTION
**Pull request by nipunn1313**
Additionally - update usage of ONCE_INIT

### CODE REVIEW

**Comment by nipunn1313** [comment]
Alternate option to 1230

**Comment by nipunn1313** [comment]
vcpkg doesn't appear to be compiling - I would guess that it requires some newer version of the windows C++ compiler - because the error seems like a compiler error

```
C:\projects\vcpkg\toolsrc\include\vcpkg/parse.h(114): error C2440: 'return': cannot convert from 'initializer list' to 'vcpkg::Parse::TextRowCol' (compiling source file ..\src\vcpkg\paragraphs.cpp) [C:\projects\vcpkg\toolsrc\vcpkglib\vcpkglib.vcxproj]
```

```
// failing to compile
TextRowCol cur_rowcol() const { return {row, column}; }
```

```
// definition of TextRowCol
namespace vcpkg::Parse
{
    struct TextRowCol
    {
        /// '0' indicates uninitialized; '1' is the first row.
        int row = 0;
        /// '0' indicates uninitialized; '1' is the first column.
        int column = 0;
    };
}
```

**Comment by nipunn1313** [comment]
there's a bunch of work that has happened to vcpkg over the past few days as well (and the appveyor.yml pulls from master of vcpkg) so it may be due to changes over there as well. It might be worth pinning to a stable version of vcpkg in the git pull command.

**Comment by sfackler** [comment]
Thanks! Yeah, the windows CI tends to be a bit flaky historically :(

**Pull request merged**
